### ISSUE TITLE
How to use protobuild with proto file containing import "google/protobuf/descriptor.proto" ?

### ISSUE THREAD

**Issue by philippbb** [vizor-games/infraworld-protobuild#4]
hi

Thank you for this plugin.

How can I use this infraworld-protobuild with a proto of mine which uses import from protobuf folder like for example:

 import "google/protobuf/descriptor.proto"

The folder for protobuf is linked via libarary to the runtime plugin but the main game module or other plugin should be able to find the descriptor proto somehow right?

I am trying to build a proto file depending on googleapi, but this is just one of the problems I encounter 👍 

kind regards

**Comment by Jake-S6** [comment]
Try using `protoc_options` in your config. For example:
```
protoc_options: ['-I=<Plugin Folder>\InfraworldRuntime\GrpcIncludes\third_party\protobuf\src']
```

* replacing `<Plugin Folder>`  with the actual path to the folder
